
friend class ESynEditError;
friend struct TCreateParamsW;
friend class TCustomSynEdit;
friend class THookedCommandHandlerEntry;
friend class TSynEdit;
friend class TSynEditMark;
friend class TSynEditMarkList;
friend class TSynEditPlugin;
friend WORD __fastcall CeilOfIntDiv(unsigned int Dividend, WORD Divisor);
friend Vcl::Controls::THintWindow* __fastcall GetScrollHint();
friend String __fastcall TrimTrailingSpaces(const String s);
