
friend class TFrmMain;
friend class TLexCharsets;
friend class TLexDefaultAttri;
friend class TLexEnclosedBy;
friend class TLexKeys;
friend String __fastcall AddInt(int AValue);
friend String __fastcall AnsiReplaceStr(const String AText, const String AFromText, const String AToText);
friend int __fastcall CompareKeys(void* Item1, void* Item2);
friend int __fastcall CompareSets(void* Item1, void* Item2);
friend String __fastcall FirstLetterCap(String s);
friend bool __fastcall IsASCIIAlphaNum(String s);
friend String __fastcall StuffString(const String Value);
friend String __fastcall ToAlphaNum(String s);
