
friend class ENoDictionaryLoaded;
friend class TDrawAutoSpellCheckPlugin;
friend struct TLanguageRec;
friend class TSynEditEx;
friend class TSynSpellCheck;
friend struct TWordRec;
friend String __fastcall DupeString(const String AText, int ACount);
friend int __fastcall ElfHash(const String Value);
friend void __fastcall Register();
friend String __fastcall TrimEx(const String sWord, WideChar chChar);
friend bool __fastcall ContainsNumbers(String sWord);
friend bool __fastcall IsNumber(const WideChar* PWORD);
// friend void __fastcall JHCMPMatrix(int X, int Y, TJHCMPLongintMatrix& LongintMatrix);
// friend void __fastcall JHCMPMatrixInit(TJHCMPLongintMatrix& LongintMatrix);
friend int __fastcall JHCMPMin(int A, int B, int C);
friend int __fastcall SortFunc(void* Item1, void* Item2);
