
friend class EheFontStockException;
friend class EheTextDrawerException;
friend struct TheFontData;
friend class TheFontStock;
friend class TheFontsInfoManager;
friend struct TheSharedFontsInfo;
friend class TheTextDrawer;
// friend TheFontsInfoManager* __fastcall GetFontsInfoManager();
// friend bool __fastcall UniversalExtTextOut(HDC DC, int X, int Y, TTextOutOptions Options, const TRect& Rect, PWideChar Str, int Count, PIntegerArray ETODist, bool UseLigatures/*# = false*/);
friend int __fastcall Min(int X, int Y);
friend void SynTextDrawer_finalization();
